
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aap-apache-job
  description: This job creates and configures am Apache VM on VSphere 
  annotations:
    backstage.io/kubernetes-id: aap-apache-job
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: neenspa/aap-apache-job
spec:
  type: api
  lifecycle: production
  owner: daniele
